package harden

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/liu97/openclaw-audit/internal/config"
	"github.com/liu97/openclaw-audit/internal/types"
)

const (
	DefaultSiteAddress      = "openclaw.example.com"
	DefaultUpstreamAddress  = "127.0.0.1:18789"
	PasswordHashPlaceholder = "REPLACE_WITH_CADDY_HASH"
)

type Options struct {
	SiteAddress  string
	Upstream     string
	AuthUser     string
	PasswordHash string
}

type Artifacts struct {
	Caddyfile string
	Guide     string
}

func Generate(loaded config.LoadedConfig, result types.ScanResult, options Options) Artifacts {
	normalized := normalizeOptions(options)
	return Artifacts{
		Caddyfile: renderCaddyfile(normalized),
		Guide:     renderGuide(loaded, result, normalized),
	}
}

func normalizeOptions(options Options) Options {
	if strings.TrimSpace(options.SiteAddress) == "" {
		options.SiteAddress = DefaultSiteAddress
	}
	if strings.TrimSpace(options.Upstream) == "" {
		options.Upstream = DefaultUpstreamAddress
	}
	if strings.TrimSpace(options.AuthUser) == "" {
		options.AuthUser = "admin"
	}
	if strings.TrimSpace(options.PasswordHash) == "" {
		options.PasswordHash = PasswordHashPlaceholder
	}
	return options
}

func renderCaddyfile(options Options) string {
	return fmt.Sprintf(`# Generated by openclaw-audit. Review before deployment.
# Caddy docs recommend hashing passwords with: caddy hash-password --plaintext 'change-me-now'
%s {
	basic_auth {
		%s %s
	}

	@blocked_methods method TRACE TRACK
	respond @blocked_methods 405

	reverse_proxy %s {
		header_up -Authorization
		header_up -X-Forwarded-User
		header_up -X-Forwarded-Email
		header_up -X-Forwarded-Groups
		header_up -X-Auth-Request-User
		header_up -X-Auth-Request-Email
	}
}
`, options.SiteAddress, options.AuthUser, options.PasswordHash, options.Upstream)
}

func renderGuide(loaded config.LoadedConfig, result types.ScanResult, options Options) string {
	var builder strings.Builder
	builder.WriteString("# OpenClaw Hardening Guide\n\n")
	builder.WriteString(fmt.Sprintf("Generated from `%s` on %s.\n\n", filepath.Clean(loaded.Path), result.GeneratedAtUTC))
	builder.WriteString("## Protective Artifacts\n\n")
	builder.WriteString("- `Caddyfile`: basic-auth protected reverse proxy in front of a loopback OpenClaw gateway.\n")
	builder.WriteString("- This setup is intended as an outer guardrail, not a replacement for OpenClaw's own token or password auth.\n\n")
	builder.WriteString("## Recommended Deployment Pattern\n\n")
	builder.WriteString(fmt.Sprintf("1. Keep OpenClaw bound to loopback and serve the Control UI locally on `%s`.\n", DefaultUpstreamAddress))
	builder.WriteString("2. Keep OpenClaw gateway auth enabled; do not replace it with trusted-proxy mode unless you have a tightly controlled proxy chain.\n")
	builder.WriteString(fmt.Sprintf("3. Put Caddy in front of the gateway at `%s` and require `basic_auth`.\n", options.SiteAddress))
	builder.WriteString("4. Strip user-assertion headers before traffic reaches OpenClaw so clients cannot spoof proxy-managed identity fields.\n")
	builder.WriteString("5. Prefer localhost, SSH tunnel, or tailnet-only access for the OpenClaw upstream even after adding Caddy.\n\n")
	builder.WriteString("## Immediate Fixes\n\n")
	for _, action := range recommendedActions(result) {
		builder.WriteString("- " + action + "\n")
	}
	builder.WriteString("\n## Current High-Priority Findings\n\n")
	highPriority := highPriorityFindings(result)
	if len(highPriority) == 0 {
		builder.WriteString("No high-priority findings detected.\n")
	} else {
		for _, finding := range highPriority {
			builder.WriteString(fmt.Sprintf("- **%s**: %s\n", finding.Title, finding.Summary))
		}
	}
	builder.WriteString("\n## Suggested OpenClaw Config Direction\n\n")
	builder.WriteString("```json\n")
	builder.WriteString("{\n")
	builder.WriteString("  \"gateway\": {\n")
	builder.WriteString("    \"bind\": \"127.0.0.1\",\n")
	builder.WriteString("    \"controlUi\": {\n")
	builder.WriteString("      \"allowInsecureAuth\": false,\n")
	builder.WriteString("      \"dangerouslyDisableDeviceAuth\": false\n")
	builder.WriteString("    }\n")
	builder.WriteString("  },\n")
	builder.WriteString("  \"fs\": {\n")
	builder.WriteString("    \"state_dir\": \"~/.openclaw\"\n")
	builder.WriteString("  }\n")
	builder.WriteString("}\n")
	builder.WriteString("```\n\n")
	builder.WriteString("## Caddy Notes\n\n")
	builder.WriteString("- Replace `REPLACE_WITH_CADDY_HASH` with the output of `caddy hash-password --plaintext 'change-me-now'`.\n")
	builder.WriteString("- Keep the upstream on loopback and use Caddy only as the public-facing layer.\n")
	builder.WriteString("- OpenClaw's dashboard and WebSocket auth still apply behind the proxy.\n")
	return builder.String()
}

func recommendedActions(result types.ScanResult) []string {
	actions := []string{
		"Move `fs.state_dir` and any credentials directory to a local non-synced path if they currently live under OneDrive, Dropbox, iCloud, or similar folders.",
		"Keep `gateway.bind` on loopback and expose OpenClaw externally only through a controlled tunnel or reverse proxy.",
		"Keep gateway token or password auth enabled even when adding an outer reverse proxy.",
	}
	if result.OpenClawVersion != "" && strings.HasPrefix(result.OpenClawVersion, "2026.2.") {
		actions = append(actions, "Upgrade OpenClaw to 2026.2.25 or newer before exposing any remote access path.")
	}
	return actions
}

func highPriorityFindings(result types.ScanResult) []types.Finding {
	selected := make([]types.Finding, 0)
	for _, finding := range result.Findings {
		if finding.Severity == types.SeverityCritical || finding.Severity == types.SeverityHigh {
			selected = append(selected, finding)
		}
		if len(selected) == 6 {
			break
		}
	}
	return selected
}
